### ISSUE TITLE
ValueError: Cannot feed value of shape (1, 480, 640, 3) for Tensor 'Placeholder:0', which has shape '(8, ?, ?, 3)'

### ISSUE THREAD

**Issue by AdamGloria** [bf777/DeepCut2RealTime#1]
We trained the training model with 8 marker points as required, but the call produced the following error: 
ValueError: Cannot feed value of shape (1, 480, 640, 3) for Tensor 'Placeholder:0', which has shape '(8, ?, ?, 3)'

**Comment by bf777** [comment]
Hi Adam, thanks for bringing this to our attention. Could you please let me know which command you ran that produced this error, and a traceback if possible? Thanks! I feel like this might be related to changes in how DeepLabCut trains data but I just need a bit more info to be sure.
